name: CI/CD

env:
  package: "${{ github.sha }}.zip"
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git clone repo
#         uses: actions/checkout@v2
#       - name: Dotnet install
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
#       - run: dotnet build HandyHost --configuration Debug
#       - name: Test
#         run: |
#           ssh -tt root@46.161.49.158
#           cd ~/handyhost/
#           mkdir test
#       - name: Executing remote command
#         uses: appleboy/ssh-action@master
#         with:
#           HOST: ${{ secrets.HOST }}
#           USERNAME: ${{ secrets.USERNAME }}
#           PORT: ${{ secrets.PORT }}
#           KEY: ${{ secrets.SSHKEY }}
#           script: |
#             ls
        
  deploy:
    runs-on: ubuntu-latest
#     needs: [build]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2
      - name: Dotnet install
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet build HandyHost --configuration Release
      - name: Zip repo
        run: zip -r ${{ env.package }} ./ -x *.git*
  
      - name: Copy folder to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.package }}
          remote: scp/handyhost
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
#       - name: Executing remote command
#         uses: appleboy/ssh-action@master
#         with:
#           HOST: ${{ secrets.HOST }}
#           USERNAME: ${{ secrets.USERNAME }}
#           PORT: ${{ secrets.PORT }}
#           KEY: ${{ secrets.SSHKEY }}
#           script: |
#             ls
